plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

permalink: :title/

twitter:
  username: zenia2020
  card: summary_large_image

paginate: 9
paginate_path: /halaman/:num/

menu:
  - nama: Informasi
    link:
      - nama: Privacy Policy
        link: /privacy-policy/
      - nama: Disclaimer
        link: /disclaimer/
      - nama: About Me
        link: /about-me/
      - nama: Daftar Isi
        link: /daftar-isi/
  - nama: WebDev
    link:
      - nama: Svelte
        link: /daftar-isi/#svelte
      - nama: JavaScript
        link: /daftar-isi/#javascript
      - nama: Jekyll
        link: /daftar-isi/#jekyll